gitmarkhubmunar/csr

src/styles/card.css
- Prevent hearts from wrapping.
- Fix indentation on some styles.
=> Fix hearts

src/QuestionDrawer.js, src/styles/slider.css
=> cleaned up css styles

src/ExpandedContent.js, src/Faq.js, src/FaqDoctor.js, src/FaqQuestion.js, src/FaqTwo.js, src/SurveyPage.js, src/styles.css, src/styles/faq.css
=> Tidy up FAQ

src/CardStatistics.js, src/ExpandedContent.js, src/Faq.js, src/FaqDoctor.js, src/FaqQuestion.js, src/FaqTwo.js, src/SurveyPage.js, src/styles.css, src/styles/card.css, src/styles/courage-health-panel.css, src/styles/faq.css
Tidy up FAQ, Top Card, Courage Panel
=> Card   courage clean up

src/HomePage.js, src/QuestionDrawer.js, src/data/CancerTypes.js
=> ch link opens to new tab

src/styles/share-card.css
pushed the share card lower to the screen to expose the card that’s
blacked out
1 breakpoint so far..
will continue to refine
=> responsive to mobile

src/CourageHealthPanel.js, src/styles/courage-health-panel.css
made it more responsive for mobile
=> reformatted courage panel

src/ButtonSurvey.js, src/styles/question-drawer.css
took off the props to button elements in buttonSurvey.js and just applied the branded color through css. 
I’m wondering if I should just add a branded color palette array
=> color consistency in survey

src/CardTitleBar.js, src/Dropdown.js, src/HomePage.js, src/QuestionDrawer.js, src/styles/card.css, src/styles/dropdown.css, src/styles/home-page.css, src/styles/title-bar.css
Elements of the stat card should now be responsive.
eased the break point at 560px w
=> Card refine1

src/QuestionDrawer.js, src/styles/slider.css
markers and ticks fixed for desktop
=> ticker refined for desktop

src/SurveyPage.js
=> Fix minor bug

src/QuestionDrawer.js, src/data/CancerTypes.js
Rename standard variables key in cancer data; conditionally show
questions
=> Rename standard variables key in cancer data; conditionally show questions

src/Card.js, src/CardStatistics.js, src/CardTitleBar.js, src/QuestionCustom.js, src/QuestionDrawer.js, src/SurveyPage.js, src/data/CancerTypes.js
- Put all user-answered data in under a `userData` key on `SurveyPage`.
- Update all components to use this new `userData` key.
- Introduce a `QuestionCustom` component to show extra variables for certain cancer types. These components add their answers to the `userData` key, alongside the default variables.
- Add unique functions for toggling mode (doctor-patient) and changing cancer type.
- Update all components to use these 2 new functions.
- Rename a poorly-named key in the cancer type data.
=> Show custom questions

src/NoCalcPatient.js, src/styles/courage-health-panel.css, src/styles/no-calc.css, src/styles/question-drawer.css, src/styles/slider.css
The margins for the survey panel is reset and responsive
The noCalc card is styled
=> Survey Panel + noCalc card refinement

src/QuestionAge.js, src/QuestionDiagnosed.js, src/QuestionDrawer.js, src/data/CancerTypes.js, src/styles/question-drawer.css, src/styles/slider.css
Generally fix up slider ticks, and restore "diagnosed" question by fixing key name in CancerTypes data
=> Fix slider ticks; restore 'diagnosis' question

src/CardStatistics.js, src/data/CancerTypes.js
Conditionally show conditional survival rate
=> Conditionally show conditional survival rate

src/NoCalcDoctor.js, src/styles/courage-health-panel.css
styles from noCalc patient is applied to the Doc version.
(may not need this panel)
=> NoCalc Doctor mode

src/SurveyPage.js
The courage health panel is turned off
=> consistent footer

src/ShareCard.js, src/styles/share-card.css
More refinement through CSS:
Desktop:
The close button sits within the margins
The share card is centered and responsive
=> share card refinement

src/styles/card.css
applied to subhead and heart icons
=> CSS centering

src/FaqTwo.js, src/Slider.js, src/SurveyPage.js, src/data/CancerTypes.js
The first hyperlink is added to FAQ
default values are updated to the diagnosis tool
=> hyperlinks + defaults

src/data/CancerTypes.js
this takes out the template for cancer type
=> CancerType edit

src/CardTitleBar.js, src/Dropdown.js, src/HomePage.js, src/styles/dropdown.css
the dropdown arrow is now consistent for both desktop and mobile
=> Title dropdown2

src/HomePage.js, src/data/CancerTypes.js, src/styles/dropdown.css, src/styles/home-page.css
the hp drop is more refined and responsive
hacked a bit in iOS to have it sit well
within the new headline layout
=> homepage dropdown refinement

src/HomePage.js, src/data/CancerTypes.js, src/styles/dropdown.css, src/styles/home-page.css
Reverts gitmarkhubmunar/csr#58
=> Revert "homepage dropdown refinement"

src/HomePage.js, src/data/CancerTypes.js, src/styles/dropdown.css, src/styles/home-page.css, src/styles/title-bar.css
Issue:
The dropdown items weren’t responsive in tablet size dimensions.
I had to separate a strange override connected from the title-bar menu.
=> Homepage update1

src/CardTitleBar.js, src/data/CancerTypes.js, src/styles/dropdown.css, src/styles/title-bar.css
CSS is reset and cleaner for mobile
=> Dropdown title update1

src/QuestionCustom.js
Try "unsetting" a custom variable by pressing the selected button again to turn it "off"
=> Try "unsetting" a custom variable by pressing the selected button again to turn it "off"

src/QuestionCustom.js, src/QuestionDiagnosed.js, src/QuestionGrade.js, src/styles/question-drawer.css
This targets certain survey buttons to stack on top of each other for
mobile screens
* bug?
For some reason, the extra variable in breast cancer disappeared. I wanted to apply this style for these type of buttons that have very long input-titles.
=> made certain buttons stack

src/QuestionCustom.js, src/QuestionDiagnosed.js, src/QuestionGrade.js, src/styles/question-drawer.css
Reverts gitmarkhubmunar/csr#73
=> Revert "made certain buttons stack"

src/QuestionCustom.js
customized variable input buttons are optimized for mobile
=> stackable styling applied to custom

src/QuestionAge.js, src/QuestionCustom.js, src/QuestionDiagnosed.js, src/QuestionGrade.js, src/QuestionSex.js, src/QuestionStage.js
this component triggers the FAQ section to disappear
=> deselect removed

src/styles/home-page.css, src/styles/question-drawer.css
an additional media query that is tablet-specific is added to the
homepage css
=> centering on tablet

src/QuestionGrade.js, src/styles/question-drawer.css
had to reset the grade input buttons  because the modal pop up changed
the css styling
=> consistent widths
